// <auto-generated />
using System;
using A2S.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace A2S.Infrastructure.Migrations
{
    [DbContext(typeof(A2SDbContext))]
    [Migration("20260124000707_AddMinimalSetsStrategy")]
    partial class AddMinimalSetsStrategy
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("A2S.Domain.Aggregates.Workout.Exercise", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("AssignedDay")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Equipment")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("OrderInDay")
                        .HasColumnType("integer");

                    b.Property<Guid>("WorkoutId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("WorkoutId");

                    b.ToTable("Exercises", (string)null);
                });

            modelBuilder.Entity("A2S.Domain.Aggregates.Workout.ExerciseProgression", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ExerciseId")
                        .HasColumnType("uuid");

                    b.Property<string>("ProgressionType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("ExerciseId")
                        .IsUnique();

                    b.ToTable("ExerciseProgressions", (string)null);

                    b.HasDiscriminator<string>("ProgressionType").HasValue("ExerciseProgression");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("A2S.Domain.Aggregates.Workout.Workout", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CurrentBlock")
                        .HasColumnType("integer");

                    b.Property<int>("CurrentWeek")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TotalWeeks")
                        .HasColumnType("integer");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Variant")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Workouts", (string)null);
                });

            modelBuilder.Entity("A2S.Domain.Entities.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("A2S.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .HasColumnType("text");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("A2S.Domain.Aggregates.Workout.LinearProgressionStrategy", b =>
                {
                    b.HasBaseType("A2S.Domain.Aggregates.Workout.ExerciseProgression");

                    b.Property<int>("BaseSetsPerExercise")
                        .HasColumnType("integer")
                        .HasColumnName("BaseSetsPerExercise");

                    b.Property<bool>("UseAmrap")
                        .HasColumnType("boolean")
                        .HasColumnName("UseAmrap");

                    b.HasDiscriminator().HasValue("Linear");
                });

            modelBuilder.Entity("A2S.Domain.Aggregates.Workout.MinimalSetsStrategy", b =>
                {
                    b.HasBaseType("A2S.Domain.Aggregates.Workout.ExerciseProgression");

                    b.Property<int>("CurrentSetCount")
                        .HasColumnType("integer")
                        .HasColumnName("MinimalSets_CurrentSetCount");

                    b.Property<string>("Equipment")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("MinimalSets_Equipment");

                    b.Property<int>("MaximumSets")
                        .HasColumnType("integer")
                        .HasColumnName("MinimalSets_MaximumSets");

                    b.Property<int>("MinimumSets")
                        .HasColumnType("integer")
                        .HasColumnName("MinimalSets_MinimumSets");

                    b.Property<int>("StartingSets")
                        .HasColumnType("integer")
                        .HasColumnName("MinimalSets_StartingSets");

                    b.Property<int>("TargetTotalReps")
                        .HasColumnType("integer")
                        .HasColumnName("MinimalSets_TargetTotalReps");

                    b.HasDiscriminator().HasValue("MinimalSets");
                });

            modelBuilder.Entity("A2S.Domain.Aggregates.Workout.RepsPerSetStrategy", b =>
                {
                    b.HasBaseType("A2S.Domain.Aggregates.Workout.ExerciseProgression");

                    b.Property<int>("CurrentSetCount")
                        .HasColumnType("integer")
                        .HasColumnName("CurrentSetCount");

                    b.Property<string>("Equipment")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Equipment");

                    b.Property<bool>("IsUnilateral")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("IsUnilateral");

                    b.Property<int>("StartingSets")
                        .HasColumnType("integer")
                        .HasColumnName("StartingSets");

                    b.Property<int>("TargetSets")
                        .HasColumnType("integer")
                        .HasColumnName("TargetSets");

                    b.HasDiscriminator().HasValue("RepsPerSet");
                });

            modelBuilder.Entity("A2S.Domain.Aggregates.Workout.Exercise", b =>
                {
                    b.HasOne("A2S.Domain.Aggregates.Workout.Workout", null)
                        .WithMany("Exercises")
                        .HasForeignKey("WorkoutId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("A2S.Domain.Aggregates.Workout.ExerciseProgression", b =>
                {
                    b.HasOne("A2S.Domain.Aggregates.Workout.Exercise", null)
                        .WithOne("Progression")
                        .HasForeignKey("A2S.Domain.Aggregates.Workout.ExerciseProgression", "ExerciseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("A2S.Domain.Aggregates.Workout.Workout", b =>
                {
                    b.OwnsMany("A2S.Domain.ValueObjects.WorkoutActivity", "CompletedActivities", b1 =>
                        {
                            b1.Property<Guid>("WorkoutId")
                                .HasColumnType("uuid");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            b1.Property<int>("BlockNumber")
                                .HasColumnType("integer");

                            b1.Property<DateTime>("CompletedAt")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<string>("Day")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<int>("WeekNumber")
                                .HasColumnType("integer");

                            b1.HasKey("WorkoutId", "__synthesizedOrdinal");

                            b1.ToTable("Workouts");

                            b1.ToJson("CompletedActivities");

                            b1.WithOwner()
                                .HasForeignKey("WorkoutId");
                        });

                    b.Navigation("CompletedActivities");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("A2S.Domain.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("A2S.Domain.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("A2S.Domain.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("A2S.Domain.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("A2S.Domain.Aggregates.Workout.LinearProgressionStrategy", b =>
                {
                    b.OwnsOne("A2S.Domain.ValueObjects.TrainingMax", "TrainingMax", b1 =>
                        {
                            b1.Property<Guid>("LinearProgressionStrategyId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Unit")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("TrainingMaxUnit");

                            b1.Property<decimal>("Value")
                                .HasColumnType("decimal(6,2)")
                                .HasColumnName("TrainingMaxValue");

                            b1.HasKey("LinearProgressionStrategyId");

                            b1.ToTable("ExerciseProgressions");

                            b1.WithOwner()
                                .HasForeignKey("LinearProgressionStrategyId");
                        });

                    b.Navigation("TrainingMax")
                        .IsRequired();
                });

            modelBuilder.Entity("A2S.Domain.Aggregates.Workout.MinimalSetsStrategy", b =>
                {
                    b.OwnsOne("A2S.Domain.ValueObjects.Weight", "CurrentWeight", b1 =>
                        {
                            b1.Property<Guid>("MinimalSetsStrategyId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Unit")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("MinimalSets_CurrentWeightUnit");

                            b1.Property<decimal>("Value")
                                .HasColumnType("decimal(6,2)")
                                .HasColumnName("MinimalSets_CurrentWeightValue");

                            b1.HasKey("MinimalSetsStrategyId");

                            b1.ToTable("ExerciseProgressions");

                            b1.WithOwner()
                                .HasForeignKey("MinimalSetsStrategyId");
                        });

                    b.Navigation("CurrentWeight")
                        .IsRequired();
                });

            modelBuilder.Entity("A2S.Domain.Aggregates.Workout.RepsPerSetStrategy", b =>
                {
                    b.OwnsOne("A2S.Domain.ValueObjects.Weight", "CurrentWeight", b1 =>
                        {
                            b1.Property<Guid>("RepsPerSetStrategyId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Unit")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("CurrentWeightUnit");

                            b1.Property<decimal>("Value")
                                .HasColumnType("decimal(6,2)")
                                .HasColumnName("CurrentWeightValue");

                            b1.HasKey("RepsPerSetStrategyId");

                            b1.ToTable("ExerciseProgressions");

                            b1.WithOwner()
                                .HasForeignKey("RepsPerSetStrategyId");
                        });

                    b.OwnsOne("A2S.Domain.ValueObjects.RepRange", "RepRange", b1 =>
                        {
                            b1.Property<Guid>("RepsPerSetStrategyId")
                                .HasColumnType("uuid");

                            b1.Property<int>("Maximum")
                                .HasColumnType("integer")
                                .HasColumnName("RepRangeMaximum");

                            b1.Property<int>("Minimum")
                                .HasColumnType("integer")
                                .HasColumnName("RepRangeMinimum");

                            b1.Property<int>("Target")
                                .HasColumnType("integer")
                                .HasColumnName("RepRangeTarget");

                            b1.HasKey("RepsPerSetStrategyId");

                            b1.ToTable("ExerciseProgressions");

                            b1.WithOwner()
                                .HasForeignKey("RepsPerSetStrategyId");
                        });

                    b.Navigation("CurrentWeight")
                        .IsRequired();

                    b.Navigation("RepRange")
                        .IsRequired();
                });

            modelBuilder.Entity("A2S.Domain.Aggregates.Workout.Exercise", b =>
                {
                    b.Navigation("Progression")
                        .IsRequired();
                });

            modelBuilder.Entity("A2S.Domain.Aggregates.Workout.Workout", b =>
                {
                    b.Navigation("Exercises");
                });
#pragma warning restore 612, 618
        }
    }
}
