// <auto-generated />
using System;
using A2S.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace A2S.Infrastructure.Migrations
{
    [DbContext(typeof(A2SDbContext))]
    [Migration("20260408204717_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("A2S.Domain.Aggregates.User.User", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(256)
                        .HasColumnType("character varying");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("A2S.Domain.Aggregates.Workout.Exercise", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("AssignedDay")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Equipment")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ExternalTemplateId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("HevyExerciseTemplateId");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("OrderInDay")
                        .HasColumnType("integer");

                    b.Property<Guid>("WorkoutId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("WorkoutId");

                    b.ToTable("Exercises", (string)null);
                });

            modelBuilder.Entity("A2S.Domain.Aggregates.Workout.ExerciseProgression", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ExerciseId")
                        .HasColumnType("uuid");

                    b.Property<string>("ProgressionType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("ExerciseId")
                        .IsUnique();

                    b.ToTable("ExerciseProgressions", (string)null);

                    b.HasDiscriminator<string>("ProgressionType").HasValue("ExerciseProgression");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("A2S.Domain.Aggregates.Workout.Workout", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CurrentBlock")
                        .HasColumnType("integer");

                    b.Property<int>("CurrentDay")
                        .HasColumnType("integer");

                    b.Property<int>("CurrentWeek")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TotalWeeks")
                        .HasColumnType("integer");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Variant")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("_blockSequence")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasColumnName("BlockSequence")
                        .HasDefaultValueSql("'[1,2,3]'::jsonb");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("UserId", "Status");

                    b.ToTable("Workouts", (string)null);
                });

            modelBuilder.Entity("A2S.Domain.Entities.ExerciseDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<int?>("DefaultRepRangeMax")
                        .HasColumnType("integer");

                    b.Property<int?>("DefaultRepRangeMin")
                        .HasColumnType("integer");

                    b.Property<int?>("DefaultSets")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("EquipmentType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool>("IsCompound")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("MuscleGroup")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("EquipmentType");

                    b.HasIndex("MuscleGroup");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("ExerciseDefinitions", (string)null);
                });

            modelBuilder.Entity("A2S.Domain.Aggregates.Workout.LinearProgressionStrategy", b =>
                {
                    b.HasBaseType("A2S.Domain.Aggregates.Workout.ExerciseProgression");

                    b.Property<int>("BaseSetsPerExercise")
                        .HasColumnType("integer")
                        .HasColumnName("BaseSetsPerExercise");

                    b.Property<int>("Tier")
                        .HasColumnType("integer");

                    b.Property<bool>("UseAmrap")
                        .HasColumnType("boolean")
                        .HasColumnName("UseAmrap");

                    b.HasDiscriminator().HasValue("Linear");
                });

            modelBuilder.Entity("A2S.Domain.Aggregates.Workout.MinimalSetsStrategy", b =>
                {
                    b.HasBaseType("A2S.Domain.Aggregates.Workout.ExerciseProgression");

                    b.Property<int>("CurrentSetCount")
                        .HasColumnType("integer")
                        .HasColumnName("MinimalSets_CurrentSetCount");

                    b.Property<string>("Equipment")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("MinimalSets_Equipment");

                    b.Property<int>("MaximumSets")
                        .HasColumnType("integer")
                        .HasColumnName("MinimalSets_MaximumSets");

                    b.Property<int>("MinimumSets")
                        .HasColumnType("integer")
                        .HasColumnName("MinimalSets_MinimumSets");

                    b.Property<int>("StartingSets")
                        .HasColumnType("integer")
                        .HasColumnName("MinimalSets_StartingSets");

                    b.Property<int>("TargetTotalReps")
                        .HasColumnType("integer")
                        .HasColumnName("MinimalSets_TargetTotalReps");

                    b.HasDiscriminator().HasValue("MinimalSets");
                });

            modelBuilder.Entity("A2S.Domain.Aggregates.Workout.RepsPerSetStrategy", b =>
                {
                    b.HasBaseType("A2S.Domain.Aggregates.Workout.ExerciseProgression");

                    b.Property<int>("CurrentSetCount")
                        .HasColumnType("integer")
                        .HasColumnName("CurrentSetCount");

                    b.Property<string>("Equipment")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Equipment");

                    b.Property<bool>("IsUnilateral")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("IsUnilateral");

                    b.Property<bool>("PendingWeightConfirmation")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("PendingWeightConfirmation");

                    b.Property<int>("StartingSets")
                        .HasColumnType("integer")
                        .HasColumnName("StartingSets");

                    b.Property<int>("TargetSets")
                        .HasColumnType("integer")
                        .HasColumnName("TargetSets");

                    b.HasDiscriminator().HasValue("RepsPerSet");
                });

            modelBuilder.Entity("A2S.Domain.Aggregates.Workout.Exercise", b =>
                {
                    b.HasOne("A2S.Domain.Aggregates.Workout.Workout", null)
                        .WithMany("Exercises")
                        .HasForeignKey("WorkoutId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("A2S.Domain.Aggregates.Workout.ExerciseProgression", b =>
                {
                    b.HasOne("A2S.Domain.Aggregates.Workout.Exercise", null)
                        .WithOne("Progression")
                        .HasForeignKey("A2S.Domain.Aggregates.Workout.ExerciseProgression", "ExerciseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("A2S.Domain.Aggregates.Workout.Workout", b =>
                {
                    b.OwnsMany("A2S.Domain.Aggregates.Workout.ProgressionAuditEntry", "AuditEntries", b1 =>
                        {
                            b1.Property<Guid>("WorkoutId")
                                .HasColumnType("uuid");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            b1.Property<int>("DayNumber")
                                .HasColumnType("integer");

                            b1.Property<Guid?>("ExerciseId")
                                .HasColumnType("uuid");

                            b1.Property<string>("ExerciseName")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)");

                            b1.Property<string>("NewValue")
                                .HasColumnType("text");

                            b1.Property<DateTime>("OccurredAt")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<string>("OldValue")
                                .HasColumnType("text");

                            b1.Property<string>("Reason")
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)");

                            b1.Property<string>("Type")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<int>("WeekNumber")
                                .HasColumnType("integer");

                            b1.HasKey("WorkoutId", "__synthesizedOrdinal");

                            b1.ToTable("Workouts");

                            b1.ToJson("AuditEntries");

                            b1.WithOwner()
                                .HasForeignKey("WorkoutId");
                        });

                    b.OwnsMany("A2S.Domain.ValueObjects.WorkoutActivity", "ArchivedActivities", b1 =>
                        {
                            b1.Property<Guid>("WorkoutId")
                                .HasColumnType("uuid");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            b1.Property<int>("BlockNumber")
                                .HasColumnType("integer");

                            b1.Property<DateTime>("CompletedAt")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<string>("Day")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<int>("WeekNumber")
                                .HasColumnType("integer");

                            b1.HasKey("WorkoutId", "__synthesizedOrdinal");

                            b1.ToTable("Workouts");

                            b1.ToJson("ArchivedActivities");

                            b1.WithOwner()
                                .HasForeignKey("WorkoutId");

                            b1.OwnsMany("A2S.Domain.ValueObjects.ExercisePerformance", "Performances", b2 =>
                                {
                                    b2.Property<Guid>("WorkoutActivityWorkoutId")
                                        .HasColumnType("uuid");

                                    b2.Property<int>("WorkoutActivity__synthesizedOrdinal")
                                        .HasColumnType("integer");

                                    b2.Property<int>("__synthesizedOrdinal")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("integer");

                                    b2.Property<DateTime>("CompletedAt")
                                        .HasColumnType("timestamp with time zone");

                                    b2.Property<Guid>("ExerciseId")
                                        .HasColumnType("uuid");

                                    b2.Property<bool>("SkipProgression")
                                        .HasColumnType("boolean");

                                    b2.HasKey("WorkoutActivityWorkoutId", "WorkoutActivity__synthesizedOrdinal", "__synthesizedOrdinal");

                                    b2.ToTable("Workouts");

                                    b2.WithOwner()
                                        .HasForeignKey("WorkoutActivityWorkoutId", "WorkoutActivity__synthesizedOrdinal");

                                    b2.OwnsMany("A2S.Domain.ValueObjects.CompletedSet", "CompletedSets", b3 =>
                                        {
                                            b3.Property<Guid>("ExercisePerformanceWorkoutActivityWorkoutId")
                                                .HasColumnType("uuid");

                                            b3.Property<int>("ExercisePerformanceWorkoutActivity__synthesizedOrdinal")
                                                .HasColumnType("integer");

                                            b3.Property<int>("ExercisePerformance__synthesizedOrdinal")
                                                .HasColumnType("integer");

                                            b3.Property<int>("__synthesizedOrdinal")
                                                .ValueGeneratedOnAdd()
                                                .HasColumnType("integer");

                                            b3.Property<int>("ActualReps")
                                                .HasColumnType("integer");

                                            b3.Property<int>("SetNumber")
                                                .HasColumnType("integer");

                                            b3.Property<bool>("WasAmrap")
                                                .HasColumnType("boolean");

                                            b3.HasKey("ExercisePerformanceWorkoutActivityWorkoutId", "ExercisePerformanceWorkoutActivity__synthesizedOrdinal", "ExercisePerformance__synthesizedOrdinal", "__synthesizedOrdinal");

                                            b3.ToTable("Workouts");

                                            b3.WithOwner()
                                                .HasForeignKey("ExercisePerformanceWorkoutActivityWorkoutId", "ExercisePerformanceWorkoutActivity__synthesizedOrdinal", "ExercisePerformance__synthesizedOrdinal");

                                            b3.OwnsOne("A2S.Domain.ValueObjects.Weight", "Weight", b4 =>
                                                {
                                                    b4.Property<Guid>("CompletedSetExercisePerformanceWorkoutActivityWorkoutId")
                                                        .HasColumnType("uuid");

                                                    b4.Property<int>("CompletedSetExercisePerformanceWorkoutActivity__synthesizedOrdinal")
                                                        .HasColumnType("integer")
                                                        .HasColumnName("CompletedSetExercisePerformanceWorkoutActivity__synthesizedOrd~");

                                                    b4.Property<int>("CompletedSetExercisePerformance__synthesizedOrdinal")
                                                        .HasColumnType("integer");

                                                    b4.Property<int>("CompletedSet__synthesizedOrdinal")
                                                        .HasColumnType("integer");

                                                    b4.Property<string>("Unit")
                                                        .IsRequired()
                                                        .HasColumnType("text");

                                                    b4.Property<decimal>("Value")
                                                        .HasColumnType("numeric");

                                                    b4.HasKey("CompletedSetExercisePerformanceWorkoutActivityWorkoutId", "CompletedSetExercisePerformanceWorkoutActivity__synthesizedOrdinal", "CompletedSetExercisePerformance__synthesizedOrdinal", "CompletedSet__synthesizedOrdinal");

                                                    b4.ToTable("Workouts");

                                                    b4.WithOwner()
                                                        .HasForeignKey("CompletedSetExercisePerformanceWorkoutActivityWorkoutId", "CompletedSetExercisePerformanceWorkoutActivity__synthesizedOrdinal", "CompletedSetExercisePerformance__synthesizedOrdinal", "CompletedSet__synthesizedOrdinal");
                                                });

                                            b3.Navigation("Weight")
                                                .IsRequired();
                                        });

                                    b2.OwnsMany("A2S.Domain.ValueObjects.PlannedSet", "PlannedSets", b3 =>
                                        {
                                            b3.Property<Guid>("ExercisePerformanceWorkoutActivityWorkoutId")
                                                .HasColumnType("uuid");

                                            b3.Property<int>("ExercisePerformanceWorkoutActivity__synthesizedOrdinal")
                                                .HasColumnType("integer");

                                            b3.Property<int>("ExercisePerformance__synthesizedOrdinal")
                                                .HasColumnType("integer");

                                            b3.Property<int>("__synthesizedOrdinal")
                                                .ValueGeneratedOnAdd()
                                                .HasColumnType("integer");

                                            b3.Property<bool>("IsAmrap")
                                                .HasColumnType("boolean");

                                            b3.Property<int>("SetNumber")
                                                .HasColumnType("integer");

                                            b3.Property<int>("TargetReps")
                                                .HasColumnType("integer");

                                            b3.HasKey("ExercisePerformanceWorkoutActivityWorkoutId", "ExercisePerformanceWorkoutActivity__synthesizedOrdinal", "ExercisePerformance__synthesizedOrdinal", "__synthesizedOrdinal");

                                            b3.ToTable("Workouts");

                                            b3.WithOwner()
                                                .HasForeignKey("ExercisePerformanceWorkoutActivityWorkoutId", "ExercisePerformanceWorkoutActivity__synthesizedOrdinal", "ExercisePerformance__synthesizedOrdinal");

                                            b3.OwnsOne("A2S.Domain.ValueObjects.Weight", "Weight", b4 =>
                                                {
                                                    b4.Property<Guid>("PlannedSetExercisePerformanceWorkoutActivityWorkoutId")
                                                        .HasColumnType("uuid");

                                                    b4.Property<int>("PlannedSetExercisePerformanceWorkoutActivity__synthesizedOrdinal")
                                                        .HasColumnType("integer")
                                                        .HasColumnName("PlannedSetExercisePerformanceWorkoutActivity__synthesizedOrdin~");

                                                    b4.Property<int>("PlannedSetExercisePerformance__synthesizedOrdinal")
                                                        .HasColumnType("integer");

                                                    b4.Property<int>("PlannedSet__synthesizedOrdinal")
                                                        .HasColumnType("integer");

                                                    b4.Property<string>("Unit")
                                                        .IsRequired()
                                                        .HasColumnType("text");

                                                    b4.Property<decimal>("Value")
                                                        .HasColumnType("numeric");

                                                    b4.HasKey("PlannedSetExercisePerformanceWorkoutActivityWorkoutId", "PlannedSetExercisePerformanceWorkoutActivity__synthesizedOrdinal", "PlannedSetExercisePerformance__synthesizedOrdinal", "PlannedSet__synthesizedOrdinal");

                                                    b4.ToTable("Workouts");

                                                    b4.WithOwner()
                                                        .HasForeignKey("PlannedSetExercisePerformanceWorkoutActivityWorkoutId", "PlannedSetExercisePerformanceWorkoutActivity__synthesizedOrdinal", "PlannedSetExercisePerformance__synthesizedOrdinal", "PlannedSet__synthesizedOrdinal");
                                                });

                                            b3.Navigation("Weight")
                                                .IsRequired();
                                        });

                                    b2.Navigation("CompletedSets");

                                    b2.Navigation("PlannedSets");
                                });

                            b1.OwnsMany("A2S.Domain.ValueObjects.ProgressionSnapshot", "ProgressionSnapshots", b2 =>
                                {
                                    b2.Property<Guid>("WorkoutActivityWorkoutId")
                                        .HasColumnType("uuid");

                                    b2.Property<int>("WorkoutActivity__synthesizedOrdinal")
                                        .HasColumnType("integer");

                                    b2.Property<int>("__synthesizedOrdinal")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("integer");

                                    b2.Property<Guid>("ExerciseId")
                                        .HasColumnType("uuid");

                                    b2.Property<string>("ExerciseName")
                                        .IsRequired()
                                        .HasMaxLength(200)
                                        .HasColumnType("character varying(200)");

                                    b2.Property<string>("ProgressionStateJson")
                                        .IsRequired()
                                        .HasColumnType("text");

                                    b2.Property<string>("ProgressionType")
                                        .IsRequired()
                                        .HasMaxLength(50)
                                        .HasColumnType("character varying(50)");

                                    b2.HasKey("WorkoutActivityWorkoutId", "WorkoutActivity__synthesizedOrdinal", "__synthesizedOrdinal");

                                    b2.ToTable("Workouts");

                                    b2.WithOwner()
                                        .HasForeignKey("WorkoutActivityWorkoutId", "WorkoutActivity__synthesizedOrdinal");
                                });

                            b1.Navigation("Performances");

                            b1.Navigation("ProgressionSnapshots");
                        });

                    b.OwnsMany("A2S.Domain.ValueObjects.WorkoutActivity", "CompletedActivities", b1 =>
                        {
                            b1.Property<Guid>("WorkoutId")
                                .HasColumnType("uuid");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            b1.Property<int>("BlockNumber")
                                .HasColumnType("integer");

                            b1.Property<DateTime>("CompletedAt")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<string>("Day")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<int>("WeekNumber")
                                .HasColumnType("integer");

                            b1.HasKey("WorkoutId", "__synthesizedOrdinal");

                            b1.ToTable("Workouts");

                            b1.ToJson("CompletedActivities");

                            b1.WithOwner()
                                .HasForeignKey("WorkoutId");

                            b1.OwnsMany("A2S.Domain.ValueObjects.ExercisePerformance", "Performances", b2 =>
                                {
                                    b2.Property<Guid>("WorkoutActivityWorkoutId")
                                        .HasColumnType("uuid");

                                    b2.Property<int>("WorkoutActivity__synthesizedOrdinal")
                                        .HasColumnType("integer");

                                    b2.Property<int>("__synthesizedOrdinal")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("integer");

                                    b2.Property<DateTime>("CompletedAt")
                                        .HasColumnType("timestamp with time zone");

                                    b2.Property<Guid>("ExerciseId")
                                        .HasColumnType("uuid");

                                    b2.Property<bool>("SkipProgression")
                                        .HasColumnType("boolean");

                                    b2.HasKey("WorkoutActivityWorkoutId", "WorkoutActivity__synthesizedOrdinal", "__synthesizedOrdinal");

                                    b2.ToTable("Workouts");

                                    b2.WithOwner()
                                        .HasForeignKey("WorkoutActivityWorkoutId", "WorkoutActivity__synthesizedOrdinal");

                                    b2.OwnsMany("A2S.Domain.ValueObjects.CompletedSet", "CompletedSets", b3 =>
                                        {
                                            b3.Property<Guid>("ExercisePerformanceWorkoutActivityWorkoutId")
                                                .HasColumnType("uuid");

                                            b3.Property<int>("ExercisePerformanceWorkoutActivity__synthesizedOrdinal")
                                                .HasColumnType("integer");

                                            b3.Property<int>("ExercisePerformance__synthesizedOrdinal")
                                                .HasColumnType("integer");

                                            b3.Property<int>("__synthesizedOrdinal")
                                                .ValueGeneratedOnAdd()
                                                .HasColumnType("integer");

                                            b3.Property<int>("ActualReps")
                                                .HasColumnType("integer");

                                            b3.Property<int>("SetNumber")
                                                .HasColumnType("integer");

                                            b3.Property<bool>("WasAmrap")
                                                .HasColumnType("boolean");

                                            b3.HasKey("ExercisePerformanceWorkoutActivityWorkoutId", "ExercisePerformanceWorkoutActivity__synthesizedOrdinal", "ExercisePerformance__synthesizedOrdinal", "__synthesizedOrdinal");

                                            b3.ToTable("Workouts");

                                            b3.WithOwner()
                                                .HasForeignKey("ExercisePerformanceWorkoutActivityWorkoutId", "ExercisePerformanceWorkoutActivity__synthesizedOrdinal", "ExercisePerformance__synthesizedOrdinal");

                                            b3.OwnsOne("A2S.Domain.ValueObjects.Weight", "Weight", b4 =>
                                                {
                                                    b4.Property<Guid>("CompletedSetExercisePerformanceWorkoutActivityWorkoutId")
                                                        .HasColumnType("uuid");

                                                    b4.Property<int>("CompletedSetExercisePerformanceWorkoutActivity__synthesizedOrdinal")
                                                        .HasColumnType("integer")
                                                        .HasColumnName("CompletedSetExercisePerformanceWorkoutActivity__synthesizedOrd~");

                                                    b4.Property<int>("CompletedSetExercisePerformance__synthesizedOrdinal")
                                                        .HasColumnType("integer");

                                                    b4.Property<int>("CompletedSet__synthesizedOrdinal")
                                                        .HasColumnType("integer");

                                                    b4.Property<string>("Unit")
                                                        .IsRequired()
                                                        .HasColumnType("text");

                                                    b4.Property<decimal>("Value")
                                                        .HasColumnType("numeric");

                                                    b4.HasKey("CompletedSetExercisePerformanceWorkoutActivityWorkoutId", "CompletedSetExercisePerformanceWorkoutActivity__synthesizedOrdinal", "CompletedSetExercisePerformance__synthesizedOrdinal", "CompletedSet__synthesizedOrdinal");

                                                    b4.ToTable("Workouts");

                                                    b4.WithOwner()
                                                        .HasForeignKey("CompletedSetExercisePerformanceWorkoutActivityWorkoutId", "CompletedSetExercisePerformanceWorkoutActivity__synthesizedOrdinal", "CompletedSetExercisePerformance__synthesizedOrdinal", "CompletedSet__synthesizedOrdinal");
                                                });

                                            b3.Navigation("Weight")
                                                .IsRequired();
                                        });

                                    b2.OwnsMany("A2S.Domain.ValueObjects.PlannedSet", "PlannedSets", b3 =>
                                        {
                                            b3.Property<Guid>("ExercisePerformanceWorkoutActivityWorkoutId")
                                                .HasColumnType("uuid");

                                            b3.Property<int>("ExercisePerformanceWorkoutActivity__synthesizedOrdinal")
                                                .HasColumnType("integer");

                                            b3.Property<int>("ExercisePerformance__synthesizedOrdinal")
                                                .HasColumnType("integer");

                                            b3.Property<int>("__synthesizedOrdinal")
                                                .ValueGeneratedOnAdd()
                                                .HasColumnType("integer");

                                            b3.Property<bool>("IsAmrap")
                                                .HasColumnType("boolean");

                                            b3.Property<int>("SetNumber")
                                                .HasColumnType("integer");

                                            b3.Property<int>("TargetReps")
                                                .HasColumnType("integer");

                                            b3.HasKey("ExercisePerformanceWorkoutActivityWorkoutId", "ExercisePerformanceWorkoutActivity__synthesizedOrdinal", "ExercisePerformance__synthesizedOrdinal", "__synthesizedOrdinal");

                                            b3.ToTable("Workouts");

                                            b3.WithOwner()
                                                .HasForeignKey("ExercisePerformanceWorkoutActivityWorkoutId", "ExercisePerformanceWorkoutActivity__synthesizedOrdinal", "ExercisePerformance__synthesizedOrdinal");

                                            b3.OwnsOne("A2S.Domain.ValueObjects.Weight", "Weight", b4 =>
                                                {
                                                    b4.Property<Guid>("PlannedSetExercisePerformanceWorkoutActivityWorkoutId")
                                                        .HasColumnType("uuid");

                                                    b4.Property<int>("PlannedSetExercisePerformanceWorkoutActivity__synthesizedOrdinal")
                                                        .HasColumnType("integer")
                                                        .HasColumnName("PlannedSetExercisePerformanceWorkoutActivity__synthesizedOrdin~");

                                                    b4.Property<int>("PlannedSetExercisePerformance__synthesizedOrdinal")
                                                        .HasColumnType("integer");

                                                    b4.Property<int>("PlannedSet__synthesizedOrdinal")
                                                        .HasColumnType("integer");

                                                    b4.Property<string>("Unit")
                                                        .IsRequired()
                                                        .HasColumnType("text");

                                                    b4.Property<decimal>("Value")
                                                        .HasColumnType("numeric");

                                                    b4.HasKey("PlannedSetExercisePerformanceWorkoutActivityWorkoutId", "PlannedSetExercisePerformanceWorkoutActivity__synthesizedOrdinal", "PlannedSetExercisePerformance__synthesizedOrdinal", "PlannedSet__synthesizedOrdinal");

                                                    b4.ToTable("Workouts");

                                                    b4.WithOwner()
                                                        .HasForeignKey("PlannedSetExercisePerformanceWorkoutActivityWorkoutId", "PlannedSetExercisePerformanceWorkoutActivity__synthesizedOrdinal", "PlannedSetExercisePerformance__synthesizedOrdinal", "PlannedSet__synthesizedOrdinal");
                                                });

                                            b3.Navigation("Weight")
                                                .IsRequired();
                                        });

                                    b2.Navigation("CompletedSets");

                                    b2.Navigation("PlannedSets");
                                });

                            b1.OwnsMany("A2S.Domain.ValueObjects.ProgressionSnapshot", "ProgressionSnapshots", b2 =>
                                {
                                    b2.Property<Guid>("WorkoutActivityWorkoutId")
                                        .HasColumnType("uuid");

                                    b2.Property<int>("WorkoutActivity__synthesizedOrdinal")
                                        .HasColumnType("integer");

                                    b2.Property<int>("__synthesizedOrdinal")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("integer");

                                    b2.Property<Guid>("ExerciseId")
                                        .HasColumnType("uuid");

                                    b2.Property<string>("ExerciseName")
                                        .IsRequired()
                                        .HasMaxLength(200)
                                        .HasColumnType("character varying(200)");

                                    b2.Property<string>("ProgressionStateJson")
                                        .IsRequired()
                                        .HasColumnType("text");

                                    b2.Property<string>("ProgressionType")
                                        .IsRequired()
                                        .HasMaxLength(50)
                                        .HasColumnType("character varying(50)");

                                    b2.HasKey("WorkoutActivityWorkoutId", "WorkoutActivity__synthesizedOrdinal", "__synthesizedOrdinal");

                                    b2.ToTable("Workouts");

                                    b2.WithOwner()
                                        .HasForeignKey("WorkoutActivityWorkoutId", "WorkoutActivity__synthesizedOrdinal");
                                });

                            b1.Navigation("Performances");

                            b1.Navigation("ProgressionSnapshots");
                        });

                    b.Navigation("ArchivedActivities");

                    b.Navigation("AuditEntries");

                    b.Navigation("CompletedActivities");
                });

            modelBuilder.Entity("A2S.Domain.Aggregates.Workout.LinearProgressionStrategy", b =>
                {
                    b.OwnsOne("A2S.Domain.ValueObjects.TrainingMax", "TrainingMax", b1 =>
                        {
                            b1.Property<Guid>("LinearProgressionStrategyId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Unit")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("TrainingMaxUnit");

                            b1.Property<decimal>("Value")
                                .HasColumnType("decimal(6,2)")
                                .HasColumnName("TrainingMaxValue");

                            b1.HasKey("LinearProgressionStrategyId");

                            b1.ToTable("ExerciseProgressions");

                            b1.WithOwner()
                                .HasForeignKey("LinearProgressionStrategyId");
                        });

                    b.Navigation("TrainingMax")
                        .IsRequired();
                });

            modelBuilder.Entity("A2S.Domain.Aggregates.Workout.MinimalSetsStrategy", b =>
                {
                    b.OwnsOne("A2S.Domain.ValueObjects.Weight", "CurrentWeight", b1 =>
                        {
                            b1.Property<Guid>("MinimalSetsStrategyId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Unit")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("MinimalSets_CurrentWeightUnit");

                            b1.Property<decimal>("Value")
                                .HasColumnType("decimal(6,2)")
                                .HasColumnName("MinimalSets_CurrentWeightValue");

                            b1.HasKey("MinimalSetsStrategyId");

                            b1.ToTable("ExerciseProgressions");

                            b1.WithOwner()
                                .HasForeignKey("MinimalSetsStrategyId");
                        });

                    b.Navigation("CurrentWeight")
                        .IsRequired();
                });

            modelBuilder.Entity("A2S.Domain.Aggregates.Workout.RepsPerSetStrategy", b =>
                {
                    b.OwnsOne("A2S.Domain.ValueObjects.Weight", "CurrentWeight", b1 =>
                        {
                            b1.Property<Guid>("RepsPerSetStrategyId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Unit")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("CurrentWeightUnit");

                            b1.Property<decimal>("Value")
                                .HasColumnType("decimal(6,2)")
                                .HasColumnName("CurrentWeightValue");

                            b1.HasKey("RepsPerSetStrategyId");

                            b1.ToTable("ExerciseProgressions");

                            b1.WithOwner()
                                .HasForeignKey("RepsPerSetStrategyId");
                        });

                    b.OwnsOne("A2S.Domain.ValueObjects.Weight", "SuggestedWeight", b1 =>
                        {
                            b1.Property<Guid>("RepsPerSetStrategyId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Unit")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("SuggestedWeightUnit");

                            b1.Property<decimal>("Value")
                                .HasColumnType("decimal(6,2)")
                                .HasColumnName("SuggestedWeightValue");

                            b1.HasKey("RepsPerSetStrategyId");

                            b1.ToTable("ExerciseProgressions");

                            b1.WithOwner()
                                .HasForeignKey("RepsPerSetStrategyId");
                        });

                    b.OwnsOne("A2S.Domain.ValueObjects.RepRange", "RepRange", b1 =>
                        {
                            b1.Property<Guid>("RepsPerSetStrategyId")
                                .HasColumnType("uuid");

                            b1.Property<int>("Maximum")
                                .HasColumnType("integer")
                                .HasColumnName("RepRangeMaximum");

                            b1.Property<int>("Minimum")
                                .HasColumnType("integer")
                                .HasColumnName("RepRangeMinimum");

                            b1.HasKey("RepsPerSetStrategyId");

                            b1.ToTable("ExerciseProgressions");

                            b1.WithOwner()
                                .HasForeignKey("RepsPerSetStrategyId");
                        });

                    b.Navigation("CurrentWeight");

                    b.Navigation("RepRange")
                        .IsRequired();

                    b.Navigation("SuggestedWeight");
                });

            modelBuilder.Entity("A2S.Domain.Aggregates.Workout.Exercise", b =>
                {
                    b.Navigation("Progression")
                        .IsRequired();
                });

            modelBuilder.Entity("A2S.Domain.Aggregates.Workout.Workout", b =>
                {
                    b.Navigation("Exercises");
                });
#pragma warning restore 612, 618
        }
    }
}
